apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
    kubernetes.azure.com/generator: devhub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: acrworkflow1724319580806.azurecr.io/mattsawesomeshop:latest
          command: ["python /usr/src/app/manage.py runserver 0.0.0.0:8000"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
